### ISSUE TITLE
No releases/versions available

### ISSUE THREAD

**Issue by ofbeaton** [Liquipedia/VariablesLua#10]
Mediawiki page lists releases, https://www.mediawiki.org/wiki/Extension:VariablesLua#Version_history

But no releases available on github (nor are they made via branches).

Could you please make github releases so that we can download known-good releases?

**Comment by FO-nTTaX** [comment]
Master is generally stable with the MediaWiki version we currently use on Liquipedia (generally that means the current LTS) and the Extension:Variables version current at the time of the last commit. I've not been testing the extension with other Mediawiki versions, however it *should* still work. 

Guaranteeing compatibility is hard for me due to lack of testing with other MediaWiki versions and this extension not really being synchronized with Extension:Variables. Known good is therefore limited to whichever version of MediaWiki and Extension:Variables we use ourselves.

This is obviously very limited in scope, but I just don't have the manpower available to me in order of making sure things work in every combination possible. I can tag the releases, but I can't guarantee it working just by doing that.

**Comment by ofbeaton** [comment]
That's more than reasonable, thank you. All I was asking was for tagged releases to coincide with the release version numbers you documented.

Thanks.

**Comment by FO-nTTaX** [comment]
Well, I put a 1.4.0 there, I'll put another one the next time I bump the version number, no problem.
